# Generated by Django 5.2.8 on 2025-11-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_temperature', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('setpoint', models.FloatField()),
                ('pid_output', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureSetpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setpoint', models.FloatField(default=25.0)),
                ('min_setpoint', models.FloatField(default=15.0)),
                ('max_setpoint', models.FloatField(default=40.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Temperature Setpoints',
            },
        ),
    ]
